# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ankur Patil
subtitle: 'SDE @ Dream11 | MnC @ IIT (BHU) Varanasi'
keywords:
about: |
  Hey, I'm Ankur Patil. I graduated with Dual Degree (Bachelors + Masters) in
  Mathematics and Computing from the Indian Institute of Technology (BHU) Varanasi. 

  I'll win be joining Dream11 as Software Engineer 1 in mid-July 2025.

  Currently, exploring AI (LLM oriented) and Blockchain. Passionate about Software Engineering and Open Source. 

  In my free time, you'll find me on the football field — or at my laptop, diving deep into system tweaks when I’m not in the mood for something productive. I also try writing [blogs](https://ankurrev.hashnode.dev). (Still working on making it a habit.)
author: Ankur Patil
language: en
timezone: 'Asia/Kolkata'
# timeline: |
#   - [**May 2025**] Selected for [Nethermind](https://www.nethermind.io)'s Agentic Internship Program — worked on AI agent communication for [ChaosChain](https://github.com/ChaosChain)  
#   - [**Oct 2024**] Received the IIT Color Award — highest honor at IIT (BHU)
#   - [**May 2024**] Honorable Mention from Gymkhana, IIT (BHU) for impactful contributions
#   - [**May 2024**] SWE Intern at Standard Chartered, Bengaluru
#   - [**Feb 2024**] Backend Intern at [Push Protocol](https://push.org)
#   - [**Dec 2023**] Led team to Silver 🥈 in Aptos Labs Challenge, InterIIT Tech Meet 12.0
#   - [**Oct 2023**] Joined HackerRank as Problem Setter
#   - [**Mar 2023**] Linux Foundation Mentee '23 — contributed to [TestGrid](https://github.com/kubernetes-sigs/testgrid) (Google Cloud × Kubernetes)
#   - [**Feb 2023**] Led team to Silver 🥈 — MetaMask Snap Hackathon, InterIIT Tech Meet 11.0
#   - [**Oct 2022**] Research Intern at [Silence Laboratories](https://www.silencelaboratories.com), a cryptography-focused startup in Singapore specializing in secure computations
#   - [**June 2022**] Software Engineer Intern at [Element](https://element.io) 
#   - [**May 2022**] Summer of Bitcoin '23 — contributed to [Specter Desktop](https://github.com/cryptoadvance/specter-desktop)


# Color Scheme
theme_config:
  colorscheme: light

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ankur12-16.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date
  pagination_dir: page
  layout: ["index", "archive"]

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/ankur12-1610/ankur12-1610.github.io.git
  branch: hexo-site
  message: 'Deploy'